package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "manifold_sample",
    srcs = [
        "src/main.cc",
    ],
    linkopts = ["-lignition-math2"],
    copts = ["-I/usr/include/ignition/math2", "-std=c++11"],
    deps = [
    ], 
)
