cc_binary(
	name = "sample",
	srcs = glob(
		["src/*.cc"]
	),
	deps = [
        "//drake/automotive/maliput/api",
        "//drake/automotive/maliput/monolane",
        "//drake/automotive/maliput/utility",
	],
)