# You need to specify a particular target
#--------------------------------------------------------------------------
# Stable and local targets
.PHONY: drake
drake:
	docker build ${DOCKER_ARGS} -t drake drake